sudo: required 
language: generic 

services:
 -docker

before_install:
 -docker build -f Dockerfile.dev dancingdumpling/frontend . 

script:
 -docker run -e CI=true dancingdumpling/frontend npm run test 