sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dancingdumpling/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dancingdumpling/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-496472651608"
  bucket_path: "docker-react"
  on:
    branch: master